[package]
name = "rust_study"
version = "0.1.0"
authors = ["sxend <arimitsu.k+github@gmail.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
tokio-io = "0.1.2"
tokio-core = "0.1.8"
iron = "0.5.1"
router = "0.5.1"