version: 2
jobs:
  build:
    docker:
      - image: sxend/ubuntu:16.04.4
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: ln -s /root/.cargo/bin/cargo /bin/cargo
      - run: cargo test