version: 2
jobs:
  build:
    docker:
      - image: sxend/ubuntu:16.04.4
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$PATH:/root/.cargo/bin' >> /root/.bashrc && echo $PATH
      - run: echo $PATH
      - run: ls -al /root/.cargo/bin
      - run: cargo test